# OpenAI Configuration
openai:
  embedding_model: "text-embedding-ada-002"
  model: "gpt-4o"
  api_key: "***"
  base_url: "***"

# GLM Configuration
glm:
  model: "glm-4-plus"
  api_key: "***"
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  embedding_model: "embedding-3"

# Deepseek Configuration
deepseek:
  model: "deepseek-chat"
  api_key: "***"
  base_url: "https://api.deepseek.com"

# Model Parameters
model_params:
  openai_embedding_dim: 1536
  glm_embedding_dim: 2048
  max_token_size: 8192

# ASTRA Configuration
astra:
  working_dir: "results"
  language: "english"
  enable_llm_cache: false
  embedding_batch_num: 6
  embedding_func_max_async: 8
  enable_naive_rag: false
  chunk_token_size: 1200
  entity_extract_max_gleaning: 1
  #evidence token limit for each retrieval source
  max_token_for_text_unit: 10000
  max_token_for_graph: 10000
  max_token_for_summary: 10000
  # if true, run macro traversal on document tree (and leaf detail traversal)
  enable_tree_traversal: false
  #number of entity/relation from vector retrieval
  detail_top_k_entity: 20
  detail_top_k_relation: 20
  macro_top_k_entity: 10
  macro_top_k_relation: 10
  #number of entity/relation from keyword retrieval
  keyword_top_k_entity: 20
  keyword_top_k_relation: 20


  